# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
