# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-16 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wiki.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiCraftProduct',
            fields=[
                ('id_wikiCraftProduct', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=2048)),
                ('count', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to=wiki.models.get_image_path)),
                ('deleted', models.BooleanField(default=0)),
                ('x_created', models.DateTimeField(auto_now_add=True)),
                ('x_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiCraftProductType',
            fields=[
                ('id_wikiCraftProductType', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('x_created', models.DateTimeField(auto_now_add=True)),
                ('x_modified', models.DateTimeField(auto_now=True)),
                ('x_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WikiItem',
            fields=[
                ('id_wikiItem', models.AutoField(primary_key=True, serialize=False)),
                ('id_map_coordinate', models.IntegerField(default=None)),
                ('name', models.CharField(max_length=128)),
                ('unique_item', models.BooleanField(default=0)),
                ('comment', models.CharField(max_length=2048)),
                ('deleted', models.BooleanField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=wiki.models.get_image_path)),
                ('x_created', models.DateTimeField(auto_now_add=True)),
                ('x_modified', models.DateTimeField(auto_now=True)),
                ('x_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='wikicraftproduct',
            name='id_wikiCraftProductType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.WikiCraftProductType'),
        ),
        migrations.AddField(
            model_name='wikicraftproduct',
            name='id_wikiItem',
            field=models.ManyToManyField(to='wiki.WikiItem'),
        ),
        migrations.AddField(
            model_name='wikicraftproduct',
            name='x_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
