# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-16 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiitem',
            name='comment',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='wikiitem',
            name='id_map_coordinate',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
