# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-21 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20180116_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikicraftproduct',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wikiitem',
            name='id_wikiCraftProductType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.WikiCraftProductType'),
        ),
    ]
