# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-08 16:24
from __future__ import unicode_literals
import datetime

from django.db import models, migrations


def load_stores(apps, schema_editor):
    wiki = apps.get_model("wiki", "WikiCraftProductType")
    now = datetime.datetime.now()
    wiki_insert = wiki(id_wikiCraftProductType=1, name='Items', x_created=now, x_user_id=1)

    wiki_insert.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20180121_1457'),
    ]

    operations = [
        migrations.RunPython(load_stores),
    ]