# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-06-22 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlock',
            fields=[
                ('id_category_block', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=2048)),
                ('show', models.BooleanField(default=True)),
                ('x_created', models.DateTimeField(auto_now_add=True)),
                ('x_modified', models.DateTimeField(auto_now=True)),
                ('access_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.AccessRight')),
                ('x_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
