# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-06-22 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_categoryblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id_category_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.CategoryBlock'),
        ),
    ]
