# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-22 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
