# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-06-09 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttasks',
            name='description_for_programmer',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
