# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-10 19:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPosts',
            fields=[
                ('id_board_post', models.AutoField(primary_key=True, serialize=False)),
                ('id_parent_board_post', models.IntegerField(default=None)),
                ('text', models.CharField(max_length=1024)),
                ('x_created', models.DateTimeField(auto_now_add=True)),
                ('x_modified', models.DateTimeField(auto_now=True)),
                ('x_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
