# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-10 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardPosts',
            new_name='posts',
        ),
    ]
