# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-10 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20171210_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='id_parent_board_post',
            new_name='id_board_post_parent',
        ),
    ]
