# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-25 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20171210_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.CharField(max_length=2048),
        ),
    ]
